Reservation: Reservation.o ReservationSystem.o Flight.o main.o
	g++ Reservation.o ReservationSystem.o main.o Flight.o -o Reservation
	
Reservation.o: Reservation.cpp
	g++ -c Reservation.cpp
	
ReservationSystem.o: ReservationSystem.cpp	
	g++ -c ReservationSystem.cpp
	
Flight.o: Flight.cpp	
	g++ -c Flight.cpp
	
main.o: main.cpp	
	g++ -c main.cpp